version: "3.7"

networks:
  api-connect:
      driver: bridge

services:
  db-postgresql-dev:
    image: bitnami/postgresql:12
    container_name: db-postgresql-dev
    restart: unless-stopped
    volumes:
      - db_postgresql_data_dev:/bitnami/postgresql
    environment:
      POSTGRESQL_DATABASE: vuttr-dev
      POSTGRESQL_PASSWORD: postgres
    networks:
      - api-connect
    ports:
      - 55432:5432

  api:
    container_name: api-container
    image: node:14
    working_dir: /usr/src/vuttr-api
    restart: unless-stopped
    depends_on:
      - db-postgresql-dev
    command: bash -c "npm install --only=prod && npm run debug"
    volumes:
      - ./dist/:/usr/src/vuttr-api/dist/
      - ./package.json:/usr/src/vuttr-api/package.json
      - ./ormconfig.js:/usr/src/vuttr-api/ormconfig.js
      - ./.env:/usr/src/vuttr-api/.env
    networks:
      - api-connect
    ports:
      - ${API_PORT}:${API_PORT}
      - 9222:9222

volumes:
  db_postgresql_data_dev:
